# Generated by Django 3.1.7 on 2021-04-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PostUpdatedBy',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='PostUpdatedDate',
            field=models.DateField(max_length=150, null=True),
        ),
    ]
