# Generated by Django 3.1.7 on 2021-04-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0002_auto_20210404_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PostDate',
            field=models.DateTimeField(max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='PostUpdatedDate',
            field=models.DateTimeField(max_length=150, null=True),
        ),
    ]
